### ISSUE TITLE
splash image moves a little from top to bottom

### ISSUE THREAD

**Issue by SergiOnGit** [zoontek/react-native-bootsplash#146]
### 💻 My environment

- react-native-bootsplash version: @next
- react-native version: latest
- Platform: android
- OS version: android 10
- Device: brand xiaomi mi 10 lite
- Simulator: no
- Android Studio version: latest
- Android buildToolsVersion: 29
- Xcode version: ?

### 🕵️‍♂️ Reproducing the issue

When i open an app splash image shows then it moves down maybe 10px. Or maybe it isn't moving it just shows again in this position. I tried to regenerate images but doesn't help. I see one related issue but on IOS. Here is image https://user-images.githubusercontent.com/34116285/77246335-a5f6c400-6c69-11ea-820d-406ecaed7c05.gif

How can i fix this?

**Comment by zoontek** [comment]
@SergiOnGit Please publish all your config files.

**Comment by SergiOnGit** [comment]
@zoontek Which config files do you mean? I am using latest 3.0.0 version and it doesn't have many configs, i just followed installation guide and then run splash generation command.

**Comment by zoontek** [comment]
It was just in case you applied more than what's in the README.

That's probably linked to MIUI and custom interfaces. I personally only have a Xiaomi 12 (with Android One: stock interface) and a Nexus 5, so I can't reproduce it.
I might have an idea, would be glad if you can try the fix.

**Comment by SergiOnGit** [comment]
@zoontek Tell me your idea and i'll try. I like this plugin and want to fix it, but i don't have native coding knowledge.

**Comment by zoontek** [comment]
@SergiOnGit I will replace Linear with RelativeLayout on a branch so you can test.

**Comment by zoontek** [comment]
@SergiOnGit I just published version `3.0.0-alpha.2`. Could you try it and see if it fixes your issue?

**Comment by SergiOnGit** [comment]
@zoontek  Thanks for trying. I have tested it but still the same.

**Comment by zoontek** [comment]
@SergiOnGit I will need a device with MIUI to debug this.

**Comment by efstathiosntonas** [comment]
This is definitely a MIUI issue, same happens on Xiaomi Note 8.

**Comment by SergiOnGit** [comment]
@zoontek Does the same happen on stable 2 version? Is it worth to try?

**Comment by efstathiosntonas** [comment]
@SergiOnGit the same happens on v2

**Comment by zoontek** [comment]
Try this: https://github.com/zoontek/react-native-bootsplash/issues/52#issuecomment-580366701

**Comment by SergiOnGit** [comment]
@zoontek I played around your pointed answer and could make it work. See my styles.xml snippet

```
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="colorAccent">#2273C8</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowTranslucentStatus">true</item>
        <item name="android:background">@drawable/bootsplash</item>
    </style>
```

Only those two lines are needed:

        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowTranslucentStatus">true</item>

You can add it to readme.

Thanks for fast responses.

**Comment by zoontek** [comment]
Cool! I will add some informations about MIUI on the README as soon as possible.

**Comment by stevecode21** [comment]
I have the same issue here.

`<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="android:textColor">#000000</item>
    </style>

    
    
    <style name="BootTheme" parent="AppTheme">
        
        <item name="android:background">@drawable/bootsplash</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:windowTranslucentStatus">true</item>
    </style>
</resources>`

That's my styles.xml file but it doesn't work.

**Comment by airam666** [comment]
this same issue happened to me with a OnePlus 6T FW 11.0 it moves up and if I make the image go fullscreen it stretches real bad
