### ISSUE TITLE
Support for react-native 0.79.0

### ISSUE THREAD

**Issue by mjmccull0** [zoontek/react-native-bootsplash#690]
### Why it is needed?

React Native 0.79.0 has been released.  The following code block shows React Native Upgrade Helper's suggested changes to `AppDelegate.swift`.

```
import UIKit
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider

@main
class AppDelegate: UIResponder, UIApplicationDelegate {
  var window: UIWindow?

  var reactNativeDelegate: ReactNativeDelegate?
  var reactNativeFactory: RCTReactNativeFactory?

  func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    let delegate = ReactNativeDelegate()
    let factory = RCTReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory

    window = UIWindow(frame: UIScreen.main.bounds)

    factory.startReactNative(
      withModuleName: "RnDiffApp",
      in: window,
      launchOptions: launchOptions
    )

    return true
  }
}

class ReactNativeDelegate: RCTDefaultReactNativeFactoryDelegate {
  override func sourceURL(for bridge: RCTBridge) -> URL? {
    self.bundleURL()
  }

  override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
}
```

The current steps to to setup react-native-bootsplash with `AppDelegate.swift` are the following.

```
import ReactAppDependencyProvider
import RNBootSplash // ⬅️ add this import

// …

@main
class AppDelegate: RCTAppDelegate {
  // …

  // ⬇️ override this method
  override func customize(_ rootView: RCTRootView!) {
    super.customize(rootView)
    RNBootSplash.initWithStoryboard("BootSplash", rootView: rootView) // ⬅️ initialize the splash screen
  }
}
```

Given the new `AppDelegate` class, `customize` isn't an overridable method and `super.customize` references a non-existent method.  Adding support for react-native 0.79.0 or documentation for how to configure `AppDelegate.swift` would be much appreciated

### Code sample

```js

```

**Comment by hatamsoyunov** [comment]
```
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
  ...

    RNBootSplash.initWithStoryboard("BootSplash", rootView: window?.rootViewController?.view) // Init BootSplash

    return true
  }
}
```
I changed it like this and now it works.

**Comment by chramos** [comment]
I'm facing issues in the android

/MainActivity.kt:25:3 'onCreate' overrides nothing.

```kotlin
class MainActivity : ReactActivity() {
...
  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)

  override fun onCreate(savedInstanceState: Bundle) {
    RNBootSplash.init(this, R.style.BootTheme)
    super.onCreate(savedInstanceState)
  }
}
```

**Comment by zoontek** [comment]
Fixed by merging https://github.com/zoontek/react-native-bootsplash/pull/691

**Comment by zoontek** [comment]
@hatamsoyunov I recommand **not** doing this, but using `ReactNativeDelegate` `customize` like @NepeinAV recommend.

**Comment by SergiOnGit** [comment]
@zoontek This is still an issue, just upgraded to RN 0.79.2 and only thing that works is hatamsoyunov's fix. As you said, you don't recommend to use it. Can you look into it? I have expo modules installed. Maybe this is the problem.

**Comment by zoontek** [comment]
@SergiOnGit The example app is [running on 0.79](https://github.com/zoontek/react-native-bootsplash/blob/master/example/package.json#L18) without any issue + the README and the expo plugin has been updated.

**Comment by SergiOnGit** [comment]
@zoontek I have deleted derivedData folder, but still the same: AppDelegate.swift:70:17 Method does not override any method from its superclass

**Comment by SergiOnGit** [comment]
Fully updated project, RN 0.79.2 and all packages to the latest. Expo 53+

**Comment by zoontek** [comment]
Please provide a reproduction repository then

**Comment by zoontek** [comment]
@SergiOnGit If you are running Expo:

- Update to the latest version of Expo and this library
- Delete the `.expo` directory
- Cleanup Xcode caches using https://apps.apple.com/us/app/devcleaner-for-xcode/id1388020431?mt=12
- Create a new clean build (`npx expo prebuild  --clean`)

**Comment by SergiOnGit** [comment]
Tried but still the same

**Comment by joe-goodall-ticketmaster** [comment]
@zoontek these are the recommended changes to the AppDelegate.swift from Expo

https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-ios

We see the same issue as @SergiOnGit when we do this

<img width="626" alt="Image" src="https://github.com/user-attachments/assets/9ae5c1ed-4112-4e91-8fa9-bced48885cbe" />

**Comment by zoontek** [comment]
@joe-goodall-ticketmaster This isn't what [the latest version of the Expo plugin](https://github.com/zoontek/react-native-bootsplash/blob/master/src/expo.ts#L306) is doing.

**Comment by joe-goodall-ticketmaster** [comment]
@zoontek Thanks for your reply. This is our `AppDelegate.swift`. We are on the latest versions of Expo (53.0.9) and Bootsplash (6.3.8).

`import UIKit
import Expo
import React
import React_RCTAppDelegate
import ReactAppDependencyProvider
import Firebase
import RNBootSplash

@main
class AppDelegate: ExpoAppDelegate {
  var window: UIWindow?

  var reactNativeDelegate: ReactNativeDelegate?
  var reactNativeFactory: RCTReactNativeFactory?

  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    FirebaseApp.configure()
    let delegate = ReactNativeDelegate()
    let factory = ExpoReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory
    bindReactNativeFactory(factory)
    window = UIWindow(frame: UIScreen.main.bounds)

    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions
    )

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    
  }
}

class ReactNativeDelegate: ExpoReactNativeFactoryDelegate {
  override func sourceURL(for bridge: RCTBridge) -> URL? {
    bridge.bundleURL ?? bundleURL()
  }

  internal override func bundleURL() -> URL? {
#if DEBUG
    RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: ".expo/.virtual-metro-entry")
#else
    Bundle.main.url(forResource: "main", withExtension: "jsbundle")
#endif
  }
  
  override func customize(_ rootView: RCTRootView) {
    super.customize(rootView)
    RNBootSplash.initWithStoryboard("BootSplash", rootView: rootView) // ⬅️ initialize the splash screen
  }
}

`

We're still seeing this error in Xcode

<img width="630" alt="Image" src="https://github.com/user-attachments/assets/2523bec1-3c73-4693-a030-0eaa7d0f057b" />

**Comment by zoontek** [comment]
@joe-goodall-ticketmaster Use the expo plugin?

**Comment by joe-goodall-ticketmaster** [comment]
> [@joe-goodall-ticketmaster](https://github.com/joe-goodall-ticketmaster) Use the expo plugin instead

Tried this but didn't work as we're a bare react native app (although now using expo-updates) so followed [this](https://github.com/zoontek/react-native-bootsplash?tab=readme-ov-file#ios-react-native-079) guide rather than [this](https://github.com/zoontek/react-native-bootsplash?tab=readme-ov-file#with-expo).

**Comment by joe-goodall-ticketmaster** [comment]
@SergiOnGit did you manage to get this working?

@zoontek our set up is a bare react native app (react native 0.79.1, bootsplash 6.3.8) but due to using expo-updates we've had to install the Expo SDK (53) and [make changes](https://docs.expo.dev/bare/installing-expo-modules/#configuration-for-ios) to the AppDelegate.swift which seems to have affected things.

**Comment by zoontek** [comment]
@joe-goodall-ticketmaster Then put this in `class ReactNativeDelegate: ExpoReactNativeFactoryDelegate`

```swift
public override func customize(_ rootView: UIView) {
  super.customize(rootView)
  RNBootSplash.initWithStoryboard("BootSplash", rootView: rootView)
}
```

That's what the Expo plugin is doing for Expo 53
